export const browserCoreExamples = [
  "dewbot browser status",
  "dewbot browser start",
  "dewbot browser stop",
  "dewbot browser tabs",
  "dewbot browser open https://example.com",
  "dewbot browser focus abcd1234",
  "dewbot browser close abcd1234",
  "dewbot browser screenshot",
  "dewbot browser screenshot --full-page",
  "dewbot browser screenshot --ref 12",
  "dewbot browser snapshot",
  "dewbot browser snapshot --format aria --limit 200",
  "dewbot browser snapshot --efficient",
  "dewbot browser snapshot --labels",
];

export const browserActionExamples = [
  "dewbot browser navigate https://example.com",
  "dewbot browser resize 1280 720",
  "dewbot browser click 12 --double",
  'dewbot browser type 23 "hello" --submit',
  "dewbot browser press Enter",
  "dewbot browser hover 44",
  "dewbot browser drag 10 11",
  "dewbot browser select 9 OptionA OptionB",
  "dewbot browser upload /tmp/file.pdf",
  'dewbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "dewbot browser dialog --accept",
  'dewbot browser wait --text "Done"',
  "dewbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "dewbot browser console --level error",
  "dewbot browser pdf",
];
