#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${DEWBOT_INSTALL_E2E_IMAGE:-${DEWBOT_INSTALL_E2E_IMAGE:-dewbot-install-e2e:local}}"
INSTALL_URL="${DEWBOT_INSTALL_URL:-${DEWBOT_INSTALL_URL:-https://dewbot.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
DEWBOT_E2E_MODELS="${DEWBOT_E2E_MODELS:-${DEWBOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e DEWBOT_INSTALL_URL="$INSTALL_URL" \
  -e DEWBOT_INSTALL_TAG="${DEWBOT_INSTALL_TAG:-${DEWBOT_INSTALL_TAG:-latest}}" \
  -e DEWBOT_E2E_MODELS="$DEWBOT_E2E_MODELS" \
  -e DEWBOT_INSTALL_E2E_PREVIOUS="${DEWBOT_INSTALL_E2E_PREVIOUS:-${DEWBOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e DEWBOT_INSTALL_E2E_SKIP_PREVIOUS="${DEWBOT_INSTALL_E2E_SKIP_PREVIOUS:-${DEWBOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
